### PR TITLE
create typedoc and insert it to api.md

### PR DESCRIPTION
**Pull request by nosuke23**
create api document with [typedoc](https://github.com/TypeStrong/typedoc) and insert the anchor to `api.md`

### CODE REVIEW

**Comment by MurakamiShinyu** [comment]
@nosuke23 Thanks for the contribution! I will check it. But please wait a while, I am now busy for preparing [Vivliostyle.js v2.18.0, see the milestone](https://github.com/vivliostyle/vivliostyle.js/milestone/3?closed=1) that includes a few changes of Vivliostyle Viewer UI and I have to also update [Vivliostyle Viewer User Guide](https://docs.vivliostyle.org/#/vivliostyle-viewer).

BTW, Vivliostyle dev community uses Slack: https://vivliostyle.org/community/ could you join?

**Comment by MurakamiShinyu** [comment]
@nosuke23
I have a question. Which is the purpose of this "Vivliostyle Core API" document?

1. for people who want to develop their own software using the Vivliostyle Core API.
2. for people who want to contribute to Vivliostyle.js core and need the documentation of Vivliostyle.js core architecture.

I think the latter (2) will make more sense because for the former (1) purpose we have already [Core API Reference](https://docs.vivliostyle.org/#/api) and real examples using Vivliostyle Core, i.e., [Vivliostyle Viewer](https://github.com/vivliostyle/vivliostyle.js/tree/master/packages/viewer), [React Vivliostyle](https://github.com/vivliostyle/vivliostyle.js/tree/master/packages/react), and [vivliostyle-print](https://github.com/vivliostyle/vivliostyle-print).

The typedoc of whole Vivliostyle Core modules can be generated with the following command in the `/packages/core` directory in the `vivliostyle.js` repository:

```
typedoc --entryPointStrategy expand ./src/vivliostyle
```

Wouldn't it be better to use this result?

----

I ask again😀: Would you like to join Vivliostyle dev community (we are using Slack: https://vivliostyle.org/community/ )? We have monthly online meetings:

- https://github.com/vivliostyle/community/issues/104

**Comment by nosuke23** [comment]
yes. I made changes to people allow to contribute Vivliostyle.js easier because typedoc is more useful to know the concepts of the internal modules and the architecture than reading codes directly (in addition, css features are so many). The added type definition files were copied from Vivliostyle.js directory, so I think the documents should be managed in the same repository. For now, I had inserted it because this repository is exist.

Thank you for inviting! I'll join.

**Comment by MurakamiShinyu** [comment]
I created a new repository https://github.com/vivliostyle/typedocs for the typedoc-generated documentation, and the vivliostyle.js/core's typedoc is available in https://vivliostyle.github.io/typedocs/core/.

I put TODO momos in the README of the repository.

I close this PR.

**Pull request closed without merging**
